export const SCENE_KEYS = {
  PRELOAD: "PRELOAD",
  TITLE: "TITLE",
  GAME: "GAME",
} as const;

export const ASSET_KEYS = {
  ALARM: "ALARM",
  SCROLL: "SCROLL",
  TOOTHBRUSH: "TOOTHBRUSH",
  BACKPACK: "BACKPACK",
  TRAIN: "TRAIN",
  CHAPTER_1_PRELUDE: "CHAPTER_1_PRELUDE",
} as const;
