// SCENE KEYS
export const SCENE_KEYS = {
  PRELOAD: "PRELOAD",
  TITLE: "TITLE",
  GAME: "GAME",
  GAME_COMPLETE: "GAME_COMPLETE",
} as const;

// FONT KEYS
export const FONT_KEYS = {
  REGULAR: "REGULAR",
} as const;

// TEXTURE_KEYS
export const TEXTURE_KEYS = {
  BUTTON: "BUTTON",
  BUTTON_DISABLED: "BUTTON_DISABLED",
  SQUARE: "SQUARE",
  TWO_THIRDS_RECTANGLE: "TWO_THIRDS_RECTANGLE",
  HALF_RECTANGLE: "HALF_RECTANGLE",
  FULL_RECTANGLE: "FULL_RECTANGLE",
} as const;

// ASSET_KEYS
export const ASSET_KEYS = {
  ALARM: "ALARM",
  SCROLL: "SCROLL",
  TOOTHBRUSH: "TOOTHBRUSH",
  BACKPACK: "BACKPACK",
  TRAIN: "TRAIN",
  CHAPTER_1_PRELUDE: "CHAPTER_1_PRELUDE",
} as const;

// SIZING CONSTANTS
export const SIZING = {
  PADDING: 10,
  PANEL_WIDTH: 342,
  PANEL_HEIGHT: 410,
  TILE_SIZE: 80,
  BUTTON_WIDTH: 90,
  BUTTON_HEIGHT: 25,
} as const;

// OUTCOME CONSTANTS
export const OUTCOMES = {
  IDEAL: "IDEAL",
  ON_TIME: "ON_TIME",
  LATE: "LATE",
  FAIL: "FAIL", // TODO: Will there be a difference between late and fail?
} as const;
