export const TILE_KEYS = {
  ALARM: "alarm",
  BACKPACK: "backpack",
  BELL: "bell",
  BOARD: "board",
  CHARGE: "charge",
  COFFEE: "coffee",
  EMAIL: "email",
  FOLDERS: "folders",
  FOOD: "food",
  GROUP: "group",
  HOODIE: "hoodie",
  KID: "kid",
  LEGO: "lego",
  LUNCHBOX: "lunchbox",
  OPEN_DOOR: "open_door",
  SCROLL: "scroll",
  TOILET: "toilet",
  TRAIN: "train",
  VAN: "van",
} as const;
